### Import NumPy

In [3]:
import numpy as np

np.__version__

'2.4.0'

### Array Shapes

In [11]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1],[2],[3],[4]])
display(arr1)
display(arr2)
print(arr1.shape)
print(arr2.shape)
display(arr1.reshape(2,2) #Changes the array structure

array([1, 2, 3, 4])

array([[1],
       [2],
       [3],
       [4]])

(4,)
(4, 1)


array([[1, 2],
       [3, 4]])

### Broadcasting

#### Broadcasting describes how NumPy performs arithmetic operations on arrays with different shapes.

#### Broadcasting is possible when, for each dimension (compared from right to left), the sizes are either equal or one of them is `1`.  The dimension with size `1` is virtually stretched to match the size of the other dimension (e.g., 3, 4, 5, etc.).

#### NumPy does not allocate new memory for the stretched values; instead, it creates a virtual view of the data, making broadcasting memory-efficient and fast.


In [13]:
add=arr1+10
add

array([11, 12, 13, 14])

In [17]:
arr1.shape

(4,)

In [16]:
arr2.shape

(4, 1)

In [18]:
arr1+arr2 # Array 1 with size 4, is treated as (1,4)

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])