### Import NumPy

In [4]:
import numpy as np

np.__version__

'2.4.0'

### Array Shapes

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1],[2],[3],[4]])
display(arr1)
display(arr2)
print(arr1.shape)
print(arr2.shape)
display(arr1.reshape(2,2)) #Changes the array structure

array([1, 2, 3, 4])

array([[1],
       [2],
       [3],
       [4]])

(4,)
(4, 1)


array([[1, 2],
       [3, 4]])

### Broadcasting

#### Broadcasting describes how NumPy performs arithmetic operations on arrays with different shapes.

#### Broadcasting is possible when, for each dimension (compared from right to left), the sizes are either equal or one of them is `1`.  The dimension with size `1` is virtually stretched to match the size of the other dimension (e.g., 3, 4, 5, etc.).

#### NumPy does not allocate new memory for the stretched values; instead, it creates a virtual view of the data, making broadcasting memory-efficient and fast.


In [13]:
add=arr1+10
add

array([11, 12, 13, 14])

In [17]:
arr1.shape

(4,)

In [16]:
arr2.shape

(4, 1)

In [18]:
arr1+arr2 # Array 1 with size 4, is treated as (1,4)

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

### Copies and Views

### Views
#### In the case of a view, the data buffer remains the same, i.e., no new memory is allocated. Therefore, any changes made to the view are reflected in the original array, and vice versa

In [41]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
viewed_arr=a[1:4] #This creates a view of the array
viewed_arr

array([2, 3, 4])

In [43]:
viewed_arr[2]=50
viewed_arr

array([ 2,  3, 50])

In [44]:
a #Change is reflected in the original array

array([ 1,  2,  3, 50,  5,  6,  7,  8,  9, 10])

### Copies
#### In the case of copy, new memory is allocated for the copied arraay. Therefore any change to the copy of an array is not reflected in the original array and vice versa

In [45]:
arr=np.array([2,4,6,8,10])
arr

array([ 2,  4,  6,  8, 10])

In [46]:
copied_arr=np.copy(arr)
copied_arr

array([ 2,  4,  6,  8, 10])

In [47]:
copied_arr[2]=100 
copied_arr

array([  2,   4, 100,   8,  10])

In [48]:
arr #No change is reflected in the original array in the case of copy

array([ 2,  4,  6,  8, 10])

#### The base attribute of an array tells if it is view or a copy. It returns original array in the case of view and None in the case of copy

In [49]:
viewed_arr.base

array([ 1,  2,  3, 50,  5,  6,  7,  8,  9, 10])

In [54]:
print(copied_arr.base)

None


### Boolean Array Indexing and Masking

In [68]:
arr

array([12, 14, 16, 18, 20])

In [71]:
arr>15

array([False, False,  True,  True,  True])

In [72]:
arr[arr>15]

array([16, 18, 20])

In [74]:
arr[arr>15]+=50
arr

array([ 12,  14, 116, 118, 120])

In [79]:
arr_2d=np.arange(30).reshape(6,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [108]:
arr_2d[2:,3]

array([12, 17, 22, 27])

In [84]:
masked_arr=arr_2d>20
masked_arr

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [111]:
masked_arr[:,0]

array([False, False, False, False, False,  True])

In [112]:
arr_2d[masked_arr[:,0]]

array([[25, 26, 27, 28, 29]])

In [123]:
combined=(arr_2d>15) & (arr_2d<20)
combined

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [134]:
arr_2d[combined]

array([16, 17, 18, 19])

In [131]:
combined[:,3]

array([False, False, False,  True, False, False])

In [133]:
arr_2d[combined[:,3]]

array([[15, 16, 17, 18, 19]])

### Universal Functions
#### NumPy universal functions are element-wise (operate logically on each element) and vectorized (compute all elements at once efficiently)

In [139]:
x1=np.array([1,2,3,4,5])
x2=np.array([6,7,8,9,10])
display(x1)
display(x2)]

array([1, 2, 3, 4, 5])

array([ 6,  7,  8,  9, 10])

#### Math operations

In [141]:
np.add(x1,x2)

array([ 7,  9, 11, 13, 15])

In [142]:
np.subtract(x1,x2)

array([-5, -5, -5, -5, -5])

In [144]:
np.matmul(x1,x2)

np.int64(130)

In [145]:
np.negative(x1)

array([-1, -2, -3, -4, -5])

In [147]:
np.power(x1,x2)

array([      1,     128,    6561,  262144, 9765625])

In [148]:
np.exp(x2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

#### Trigonometric functions

In [149]:
np.sin(x1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [150]:
np.sinh(x2)

array([  201.71315737,   548.31612327,  1490.47882579,  4051.54190208,
       11013.2328747 ])

#### Bit-twiddling functions

In [154]:
np.bitwise_and(x2,x2)

array([ 6,  7,  8,  9, 10])

In [152]:
np.invert(x1)

array([-2, -3, -4, -5, -6])

#### Comparison functions

In [156]:
np.greater(x1,x2)

array([False, False, False, False, False])

In [157]:
np.greater_equal(x2,x1)

array([ True,  True,  True,  True,  True])

In [158]:
np.maximum(x1,x2)

array([ 6,  7,  8,  9, 10])

In [159]:
np.fmin(x2,x1)

array([1, 2, 3, 4, 5])

#### Floating functions

In [160]:
np.isnan(x2)

array([False, False, False, False, False])

In [163]:
np.modf(x2)

(array([0., 0., 0., 0., 0.]), array([ 6.,  7.,  8.,  9., 10.]))

In [164]:
np.fmod(x1,x2)

array([1, 2, 3, 4, 5])

### Aggregation and Statistics

In [181]:
np.min(x1)

np.int64(1)

In [166]:
np.mean(x2)

np.float64(8.0)

In [167]:
np.std(x1) #Standard Deviation

np.float64(1.4142135623730951)

In [179]:
np.var(x1) #Variance

np.float64(2.0)

In [170]:
np.percentile(x1,80) #80th percentile

np.float64(4.2)

In [177]:
np.quantile(x2,0.4)

np.float64(7.6)

In [173]:
np.average(x2)

np.float64(8.0)

In [174]:
np.histogram(x1)

(array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1]),
 array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ]))

### Linear Algebra

In [183]:
np.dot(x1,x2)

np.int64(130)

In [189]:
a=np.array([[1,2],[3,4]])
np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [192]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [193]:
constant=np.array([3,2])
np.linalg.solve(a,constant) #Solves equation of the form Ax=B

array([-4. ,  3.5])

In [195]:
np.linalg.inv(a) #Inverse of matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [196]:
np.diagonal(a)

array([1, 4])

### Data Types in NumPy
#### Every NumPy array has a data type (dtype), which determines how elements are stored in memory.

In [199]:
np.array([1,2,3,4],dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [202]:
np.array([1,2,3,4],dtype=np.int64)

array([1, 2, 3, 4])

In [203]:
np.array([1,2,3,4],dtype=np.float32) # OR np.array([1,2,3,4],dtype='f')

array([1., 2., 3., 4.], dtype=float32)

In [208]:
np.array([1,0],dtype=np.bool)

array([ True, False])

#### Type Conversion

In [217]:
z=np.array([1,2,3,5])
print(z.dtype)
z

int64


array([1, 2, 3, 5])

In [219]:
y=z.astype(np.float64)
print(y.dtype)
y

float64


array([1., 2., 3., 5.])

### Random Module

In [240]:
np.random.rand() #Random numbers between 0 and 1 with equal probability of each

array([0.12617799, 0.55609931, 0.60078481, 0.62079181, 0.33938017])

In [242]:
np.random.rand(5)

array([0.70047692, 0.59852331, 0.15992232, 0.51392929, 0.67914866])

In [243]:
np.random.rand(2, 3)

array([[0.99167573, 0.07296277, 0.62995342],
       [0.16782121, 0.52484847, 0.06257077]])

In [245]:
np.random.random(5)

array([0.83623388, 0.12326044, 0.74308472, 0.30301576, 0.51920694])

#### Normal (Gaussian) random numbers 
##### Most values are near the mean .

In [274]:
np.random.randn() ## mean=0 in this case with Standard Deviation=1 . So numbers are mostly near to 0

-0.7249297680735126

In [278]:
np.random.normal(10,0.1,5) ## Just an extended version of randn . Here we can specify the mean and the standard deviation here mean=10 and sd=2 so values are close to 10

array([10.01676601, 10.01246742, 10.00338473, 10.00252378,  9.98514131])

#### Random Integers and Sampling

In [280]:
np.random.randint(1, 10) #One integer between 1 and 10

4

In [281]:
np.random.randint(1, 10, 5)

array([9, 9, 6, 8, 4], dtype=int32)

In [282]:
np.random.randint(1, 10, (3,3))

array([[4, 7, 4],
       [3, 9, 7],
       [8, 2, 5]], dtype=int32)

In [286]:
np.random.choice([10, 20, 30], size=1) #Chooses one value from the given sample

array([30])

In [285]:
np.random.choice([10, 20, 30], size=3)

array([20, 10, 10])

#### Shifting Vs Permutation

In [297]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [304]:
np.random.shuffle(a) #Shuffles  the original array
a

array([3, 4, 2, 1])

In [296]:
b=np.random.permutation([1,2,3,4]) #returns a new array
b

array([2, 3, 1, 4])

### Seeding

In [306]:
np.random.rand()

0.7633302030933323

In [335]:
np.random.seed(1)
np.random.rand()

0.417022004702574