# Introduction to NumPy

## What is NumPy?
#### NumPy is the findamental package for scientific computing in Python. It is basically used to perform the fast and efficient operations on large , multi-dimensional array's and matrices .It provides powerful N-Dimensional array (ndarray) and vectorized operations along with multiple built in mathematical, statitical and linear algebra functions that helps us to perform the fast operations on the array.

### Importing Numpy

In [21]:
import numpy as np

np.__version__

'2.4.0'

### 1D Array Creation and basic ndarray Properties 

In [48]:
arr1=np.array([1,2,3,4]) #1 Dimensional Array
arr2=np.array([[5,6,7,8],[1,2,3,4]])  #2 Dimensional Array and so on
print(arr1)
print(arr2)
print(type(arr1))
print("Dimensiion: ",arr2.ndim,"Shape: ",arr2.shape,"Number of elements: ", arr2.size)
complex_array=np.array([[1,2],[3,4]],dtype=complex)
print(complex_array)
print("Dimensiion: ",complex_array.ndim,"Shape: ",complex_array.shape,"Number of elements: ", complex_array.size)
copied_arr=arr1.copy()
print("Copied array: ",copied_arr)
zeros_array=np.zeros(3) # Creates array with 3 0's
ones_array=np.ones(3)  # Creates array with 3 1's
arranged_array=np.arange(4) # Creates array from 0 to 3
print(zeros_array)
print(ones_array)
print(arranged_array)
arr2[1][0]


[1 2 3 4]
[[5 6 7 8]
 [1 2 3 4]]
<class 'numpy.ndarray'>
Dimensiion:  2 Shape:  (2, 4) Number of elements:  8
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
Dimensiion:  2 Shape:  (2, 2) Number of elements:  4
Copied array:  [1 2 3 4]
[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3]


np.int64(1)

### 2D Array Creation

In [119]:
arr3=np.eye(4,4) #Creates a 2D array with 1 where m=n
displaywh(arr3)
arr4=np.diag([1,2,3]) #Creates a 2D array with diagonal elements as specified in the array
display(arr4)
copy=np.copy(arr4)
copy

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### General ndarray creation functions

In [49]:
from numpy.random import default_rng

ndarr1=np.zeros((2,3))
ndarr2=np.ones((2,3))
print(ndarr1)
print(ndarr2)
random_array=default_rng(10).random((2,3))
random_array

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[0.95600171, 0.20768181, 0.82844489],
       [0.14928212, 0.51280462, 0.1359196 ]])

### Indexing and Slicing


In [67]:
print(arr1[2])
print(arr2[1][2])
sliced_arr=arr1[:2]
print(sliced_arr)
print(arr1[0:3])
print(arr1[-3:])
arr1[2:4]
arr2[1]

3
3
[1 2]
[1 2 3]
[2 3 4]


array([1, 2, 3, 4])

### Basic Array Operations

In [ ]:
print(arr1+arr1)
print(arr2*arr2)
print(arr1/arr1)
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])
display(ar1+ar2)
display(ar1*ar2)

[2 4 6 8]
[[25 36 49 64]
 [ 1  4  9 16]]
[1. 1. 1. 1.]
[[ 6  8]
 [10 12]]


array([[ 5, 12],
       [21, 32]])

In [ ]:
print(arr1.max())
print(arr1.min())

np.int64(4)

In [ ]:
print(arr1.sum())
print(arr2.sum())
print(arr2.sum(axis=1))  #axis=0 imples row wise operations and axis=1 means column wise operations 

10


array([26, 10])

In [96]:
reversed_arr1=np.flip(arr1) #Reverses an array
reversed_arr2=np.flip(arr2)
print(reversed_arr1)
print(reversed_arr2)


[4 3 2 1]
[[4 3 2 1]
 [8 7 6 5]]


In [82]:
print(np.average(arr2[0]))
np.average(arr1)

6.5


np.float64(2.5)

In [93]:
duplicate_arr=np.array([1,2,2,3,3,4,10])
print(np.unique(duplicate_arr))
print(np.unique(duplicate_arr,return_index=True))
print(np.unique(duplicate_arr,return_counts=True))

[ 1  2  3  4 10]
(array([ 1,  2,  3,  4, 10]), array([0, 1, 3, 5, 6]))
(array([ 1,  2,  3,  4, 10]), array([1, 2, 2, 1, 1]))


In [107]:
print(arr1.reshape(2,2))
dim1_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
dim2_arr=np.array([[9,8,7],[6,5,4],[3,2,1]])
display(dim1_arr.transpose())
display(dim2_arr.transpose())
reversed_arr_rows = np.flip(dim1_arr, axis=0)
display(reversed_arr_rows)


[[1 2]
 [3 4]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### Saving and Loading NumPy Objects

In [117]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.save("data",arr) # Save the array in data.npy file
loaded_arr=np.load("data.npy")
display(loaded_arr)


array([1, 2, 3, 4, 5, 6])